// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Hdx01WfXebidxD4ISVaXJgBVJrLUYTU',
    appId: '1:718367715543:web:71bb67b4e76670b4ee8092',
    messagingSenderId: '718367715543',
    projectId: 'tabasco-escapes',
    authDomain: 'tabasco-escapes.firebaseapp.com',
    storageBucket: 'tabasco-escapes.appspot.com',
    measurementId: 'G-XME27X7HBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0cWh89t63kYI_AcCenyx-EN7DGHDuWo',
    appId: '1:718367715543:android:ec69cc818c2149c0ee8092',
    messagingSenderId: '718367715543',
    projectId: 'tabasco-escapes',
    storageBucket: 'tabasco-escapes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPkvQHaX18BVuuECyIh5pQTE8las6NYA',
    appId: '1:718367715543:ios:1792dbb29dbdbe9cee8092',
    messagingSenderId: '718367715543',
    projectId: 'tabasco-escapes',
    storageBucket: 'tabasco-escapes.appspot.com',
    iosClientId:
        '718367715543-ogp7nuj35gdgq67rg57r2atuubokmvkm.apps.googleusercontent.com',
    iosBundleId: 'tech.sitab.tabascoescapes.tabascoEscapes',
  );
}
